version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: 
      - .env.pg
    ports:
      - 5432:5423

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.pgadmin
    ports:
      - 5050:80

  client:
    build:
      context: ./client
    command: ["npm", "start"]
    ports:
     - 3000:3000
    volumes:
      - ./client/:/client
      - ./client/node_modules/:/client/node_modules
    environment:
     - CI=true
     - CHOKIDAR_USEPOLLING=true
    tty: true

  springboot:
    restart: always
    image: springboot
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - springdata:/usr/src:rw
      - ./server/:/server/
    depends_on: 
      - postgres

volumes:
  pgdata:
  springdata: